version: '2.1'
services:
  app:
    build: .
  nginx:
    image: nginx:mainline
    ports:
      - "80:80"
      - "443:443"
  postgres:
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 30s
      retries: 6
  rabbitmq:
    image: rabbitmq:3-management
    env_file: musyc.env
    volumes:
      - "./_state/rabbitmq-logs:/var/log/rabbitmq"
      - "./_state/rabbitmq-data:/var/lib/rabbitmq"


volumes:
  static-assets: