version: '3.0'
services:
  rabbitmq:
    image: rabbitmq:3-management
    env_file: musyc.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./_state/rabbitmq-logs:/var/log/rabbitmq"
      - "./_state/rabbitmq-data:/var/lib/rabbitmq"
  postgres:
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 30s
      retries: 6
    ports:
      - "5432:5432"
    volumes:
      - "./_state/postgres-data:/var/lib/postgresql/data"
    env_file: musyc.env
